-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 18:48:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL,
  `CustomerName` VARCHAR(45) NULL,
  `CustomerAddress1` VARCHAR(45) NULL,
  `CustomerAddress2` VARCHAR(45) NULL,
  `CustomerCity` VARCHAR(45) NULL,
  `CustomerState` VARCHAR(45) NULL,
  `CustomerZip` INT NULL,
  `CustomerPhone1` INT NULL,
  `CustomerPhone2` INT NULL,
  `ReferredBy` VARCHAR(45) NULL,
  `CustomerSince` DATE NULL,
  `CustomerTypeMowing` VARCHAR(45) NULL,
  `CustomerTypeLandscaping` VARCHAR(45) NULL,
  `CustomerPriorBalance` DECIMAL(10,2) NULL,
  `CustomerTotalNewCharges` DECIMAL(10,2) NULL,
  `CustomerTaxes` DECIMAL(10,2) NULL,
  `CustomerTotalCredits` DECIMAL(10,2) NULL,
  `CustomerTotalAmountDue` DECIMAL(10,2) NULL,
  `CustomerTypeOther` VARCHAR(45) NULL,
  `Notes` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `Invoice Number` INT NOT NULL,
  `Invoice Date` DATE NULL,
  `CustomerID` INT NULL,
  `InvoiceTotalAmountDue` DECIMAL(10,2) NULL,
  `InvoiceAmountRemitted` DECIMAL(10,2) NULL,
  `TotalCharges` DECIMAL(10,2) NULL,
  `TotalCredits` DECIMAL(10,2) NULL,
  `Customer_CustomerID` INT NULL,
  PRIMARY KEY (`Invoice Number`),
  INDEX `fk_Invoice_Customer_idx` (`Customer_CustomerID` ASC),
  CONSTRAINT `fk_Invoice_Customer`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InvoiceDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InvoiceDetail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InvoiceDetail` (
  `InvoiceDetailLineNumber` INT NOT NULL,
  `Invoice Number` INT NOT NULL,
  `InvoiceDetailDate` DATE NULL,
  `Description` VARCHAR(45) NULL,
  `Charges` DECIMAL(10,2) NULL,
  `Charges` DECIMAL(10,2) NULL,
  `Credits` DECIMAL(10,2) NULL,
  `Invoice_Invoice Number` INT NULL,
  PRIMARY KEY (`InvoiceDetailLineNumber`, `Invoice Number`),
  INDEX `fk_InvoiceDetail_Invoice1_idx` (`Invoice_Invoice Number` ASC),
  CONSTRAINT `fk_InvoiceDetail_Invoice1`
    FOREIGN KEY (`Invoice_Invoice Number`)
    REFERENCES `mydb`.`Invoice` (`Invoice Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
